const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o));
const names={heading:'見出し',text:'テキスト',button:'ボタン',rectangle:'四角形',circle:'円',image:'画像'};
let nextId=1,selected=null,scale=1,history=[],future=[],drag=null;
const make=(type,extra={})=>({id:nextId++,type,x:70,y:70,w:260,h:70,text:type==='heading'?'新しい見出し':type==='text'?'ここにテキストを入力してください。':type==='button'?'詳しく見る':'',fontSize:type==='heading'?36:16,color:'#272a40',background:['rectangle','circle','button'].includes(type)?'#7256e8':'transparent',radius:type==='circle'?500:type==='button'?10:0,bold:type==='heading',align:type==='button'?'center':'left',href:'',...extra});
let state={name:'はじめてのWebページ',width:1000,height:760,background:'#ffffff',elements:[make('text',{x:72,y:62,w:330,h:30,text:'YOUR NEXT CHAPTER',fontSize:14,bold:true,color:'#7456db'}),make('heading',{x:72,y:136,w:840,h:155,text:'ひらめきを、\nあなたのWebサイトに。',fontSize:57}),make('text',{x:76,y:330,w:680,h:80,text:'伝えたいことを、自由に並べよう。\n文字も、色も、レイアウトも。ここからは、あなた次第。',fontSize:20,color:'#7b7e90'}),make('button',{x:76,y:459,w:210,h:58,text:'ここからはじめる',color:'#ffffff',bold:true}),make('rectangle',{x:76,y:609,w:848,h:2,background:'#ecebf3'}),make('text',{x:76,y:643,w:650,h:32,text:'MADE WITH IMAGINATION  /  HTML STUDIO',fontSize:13,color:'#9798a7'})]};
function checkpoint(){history.push(clone(state));if(history.length>80)history.shift();future=[];updateHistory()}
function updateHistory(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function current(){return state.elements.find(e=>e.id===selected)}
function elementStyle(e){return{left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px',fontSize:e.fontSize+'px',color:e.color,background:e.background,borderRadius:e.radius+'px',fontWeight:e.bold?'700':'400',textAlign:e.align}}
function render(){const c=$('canvas');c.replaceChildren();Object.assign(c.style,{width:state.width+'px',height:state.height+'px',background:state.background});for(const e of state.elements){const el=document.createElement('div');el.className='element'+(e.id===selected?' selected':'');el.dataset.id=e.id;el.tabIndex=0;el.setAttribute('aria-label',names[e.type]+': '+(e.text||''));Object.assign(el.style,elementStyle(e));const inner=document.createElement('div');inner.className='inner';if(e.type==='image'){const img=document.createElement('img');img.src=e.src;img.alt=e.text||'画像';inner.append(img)}else{inner.textContent=e.text;if(e.type==='button'){inner.style.display='flex';inner.style.alignItems='center';inner.style.justifyContent=e.align==='left'?'flex-start':e.align==='right'?'flex-end':'center';inner.style.padding='8px'}}el.append(inner);if(e.id===selected){const tag=document.createElement('span');tag.className='element-tag';tag.textContent=names[e.type];const handle=document.createElement('span');handle.className='resize';el.append(tag,handle)}c.append(el)}fit();layers();updateHistory();$('projectName').value=state.name}
function fit(){const stage=$('stage'),z=$('zoom').value;scale=z==='fit'?Math.min(1,Math.max(.1,(stage.clientWidth-(innerWidth<760?24:64))/state.width)):Number(z);$('canvas').style.transform=`scale(${scale})`;$('canvasWrap').style.width=state.width*scale+'px';$('canvasWrap').style.height=state.height*scale+'px'}
function inspect(){const e=current();$('elementFields').hidden=!e;$('pageFields').hidden=!!e;$('inspectorTitle').textContent=e?names[e.type]:'ページ設定';$('kindBadge').textContent=e?e.type.toUpperCase():'PAGE';$('selectionStatus').textContent=e?`${names[e.type]} · ${Math.round(e.w)} × ${Math.round(e.h)}`:'パーツを選んで編集';if(e){for(const key of ['x','y','w','h','fontSize','radius','color','align','href'])$(key).value=e[key];$('content').value=e.text;$('background').value=e.background==='transparent'?'#ffffff':e.background;$('transparent').checked=e.background==='transparent';$('bold').checked=e.bold;$('linkField').hidden=e.type!=='button';$('content').parentElement.hidden=['rectangle','circle'].includes(e.type)}else{$('pageColor').value=state.background;$('pageHeight').value=state.height}}
function select(id){selected=id;render();inspect()}
function layers(){$('layerList').replaceChildren();for(const e of [...state.elements].reverse()){const b=document.createElement('button');b.textContent=(e.text||names[e.type]).replaceAll('\n',' ');b.className=e.id===selected?'active':'';b.onclick=()=>select(e.id);$('layerList').append(b)}}
function add(type,extra={}){checkpoint();const e=make(type,{x:Math.min(70,state.width-280),y:Math.round($('stage').scrollTop/scale+90),...extra});e.x=Math.max(0,e.x);state.elements.push(e);select(e.id)}
document.querySelectorAll('[data-add]').forEach(b=>{b.onclick=()=>add(b.dataset.add);b.ondragstart=ev=>ev.dataTransfer.setData('text/plain',b.dataset.add)});
$('canvas').ondragover=ev=>ev.preventDefault();$('canvas').ondrop=ev=>{ev.preventDefault();const t=ev.dataTransfer.getData('text/plain');if(!['heading','text','button','rectangle','circle'].includes(t))return;const r=$('canvas').getBoundingClientRect();add(t,{x:Math.max(0,Math.round((ev.clientX-r.left)/scale)),y:Math.max(0,Math.round((ev.clientY-r.top)/scale))})};
$('canvas').onpointerdown=ev=>{const el=ev.target.closest('.element');if(!el){select(null);return}const id=Number(el.dataset.id),resize=ev.target.classList.contains('resize');select(id);const e=current();drag={id,resize,startX:ev.clientX,startY:ev.clientY,before:clone(e),saved:false};ev.preventDefault()};
window.addEventListener('pointermove',ev=>{if(!drag)return;const dx=(ev.clientX-drag.startX)/scale,dy=(ev.clientY-drag.startY)/scale;if(!drag.saved&&Math.abs(dx)+Math.abs(dy)<2)return;if(!drag.saved){checkpoint();drag.saved=true}const e=current();if(!e)return;if(drag.resize){e.w=Math.max(20,Math.round(drag.before.w+dx));e.h=Math.max(20,Math.round(drag.before.h+dy))}else{e.x=Math.max(0,Math.min(state.width-20,Math.round(drag.before.x+dx)));e.y=Math.max(0,Math.min(state.height-20,Math.round(drag.before.y+dy)))}render();inspect()});
window.addEventListener('pointerup',()=>drag=null);window.addEventListener('pointercancel',()=>drag=null);
for(const key of ['content','x','y','w','h','fontSize','radius','color','background','align','href','bold','transparent']){$(key).addEventListener(['content','href'].includes(key)?'input':'change',()=>{const e=current();if(!e)return;checkpoint();if(key==='content')e.text=$(key).value;else if(key==='bold')e.bold=$(key).checked;else if(key==='transparent')e.background=$(key).checked?'transparent':$('background').value;else if(['x','y','w','h','fontSize','radius'].includes(key)){const value=Number($(key).value);e[key]=Math.max(['w','h'].includes(key)?20:key==='fontSize'?8:0,Math.min(key==='fontSize'?200:5000,Number.isFinite(value)?value:0))}else e[key]=$(key).value;render();if(!['content','href'].includes(key))inspect()})}
$('pageColor').onchange=()=>{checkpoint();state.background=$('pageColor').value;render()};$('pageHeight').onchange=()=>{checkpoint();state.height=Math.min(5000,Math.max(300,Number($('pageHeight').value)||760));render();inspect()};$('projectName').onchange=()=>{checkpoint();state.name=$('projectName').value.trim()||'無題のページ';render()};
function remove(){if(!current())return;checkpoint();state.elements=state.elements.filter(e=>e.id!==selected);select(null)}
$('delete').onclick=remove;$('duplicate').onclick=()=>{const e=current();if(e)add(e.type,{...clone(e),id:nextId++,x:e.x+20,y:e.y+20})};
function reorder(delta){const i=state.elements.findIndex(e=>e.id===selected),j=i+delta;if(i<0||j<0||j>=state.elements.length)return;checkpoint();[state.elements[i],state.elements[j]]=[state.elements[j],state.elements[i]];render()}
$('forward').onclick=()=>reorder(1);$('backward').onclick=()=>reorder(-1);
function undo(){if(!history.length)return;future.push(clone(state));state=history.pop();select(null)}function redo(){if(!future.length)return;history.push(clone(state));state=future.pop();select(null)}$('undo').onclick=undo;$('redo').onclick=redo;
document.addEventListener('keydown',ev=>{if(/INPUT|TEXTAREA|SELECT/.test(ev.target.tagName)||$('previewDialog').open)return;const modifier=ev.ctrlKey||ev.metaKey;if(modifier&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo();return}if(modifier&&ev.key.toLowerCase()==='y'){ev.preventDefault();redo();return}if(ev.key==='Escape'){select(null);return}if(!current())return;if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();remove()}if(ev.key.startsWith('Arrow')){ev.preventDefault();checkpoint();const e=current(),n=ev.shiftKey?10:1;e.x=Math.max(0,Math.min(state.width-20,e.x+(ev.key==='ArrowRight'?n:ev.key==='ArrowLeft'?-n:0)));e.y=Math.max(0,Math.min(state.height-20,e.y+(ev.key==='ArrowDown'?n:ev.key==='ArrowUp'?-n:0)));render();inspect()}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));$('parts').hidden=b.dataset.tab!=='parts';$('layers').hidden=b.dataset.tab!=='layers'});
document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>{checkpoint();state.width=Number(b.dataset.width);document.querySelectorAll('[data-width]').forEach(t=>t.classList.toggle('active',t===b));render();toast('キャンバス幅を変更しました。パーツの位置はそのままです。')});$('zoom').onchange=fit;new ResizeObserver(fit).observe($('stage'));
$('imageAdd').onclick=()=>$('imageInput').click();$('imageInput').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;if(file.size>8*1024*1024){toast('画像は8MB以下で選んでください');return}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){toast('PNG・JPEG・WebP・GIFを選んでください');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const w=Math.min(400,state.width-40);add('image',{src:reader.result,w,h:Math.round(w*img.height/img.width),text:file.name});toast('画像を追加しました')};img.onerror=()=>toast('この画像を読み込めませんでした');img.src=reader.result};reader.readAsDataURL(file);ev.target.value=''};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeLink(s){try{const u=new URL(s);return ['https:','http:','mailto:','tel:'].includes(u.protocol)?s:''}catch{return s.startsWith('#')?s:''}}
function html(){return '<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(state.name)+'</title><style>*{box-sizing:border-box}body{margin:0;background:'+state.background+';font-family:system-ui,sans-serif}.page{position:relative;width:'+state.width+'px;height:'+state.height+'px;margin:0 auto;overflow:hidden}.item{position:absolute;white-space:pre-wrap;line-height:1.35;overflow:hidden;text-decoration:none}img{display:block;width:100%;height:100%;object-fit:cover}@media(max-width:'+state.width+'px){.page{zoom:calc(100vw / '+state.width+'px)}}</style></head><body><main class="page">'+state.elements.map(e=>{const style=Object.entries(elementStyle(e)).map(([k,v])=>k.replace(/[A-Z]/g,l=>'-'+l.toLowerCase())+':'+v).join(';');const tag=e.type==='heading'?'h2':e.type==='button'?'a':'div';return '<'+tag+' class="item" style="margin:0;'+esc(style)+(e.type==='button'?';display:flex;align-items:center;justify-content:'+(e.align==='left'?'flex-start':e.align==='right'?'flex-end':'center')+';padding:8px':'')+'"'+(e.type==='button'?' href="'+esc(safeLink(e.href)||'#')+'"':'')+'>'+(e.type==='image'?'<img src="'+esc(e.src)+'" alt="'+esc(e.text)+'">':esc(e.text))+'</'+tag+'>'}).join('')+'</main></body></html>'}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>{download('index.html',html(),'text/html;charset=utf-8');toast('HTMLを書き出しました')};$('preview').onclick=()=>{$('previewFrame').srcdoc=html();$('previewDialog').showModal()};$('closePreview').onclick=()=>$('previewDialog').close();$('save').onclick=()=>{download('html-studio-project.json',JSON.stringify({version:1,...state},null,2),'application/json');toast('プロジェクトを保存しました')};$('load').onclick=()=>$('loadInput').click();
function validate(o){const color=v=>/^#[0-9a-f]{6}$/i.test(v);if(o.version!==1||typeof o.name!=='string'||!color(o.background)||![390,1000].includes(o.width)||!Number.isFinite(o.height)||o.height<300||o.height>5000||!Array.isArray(o.elements)||o.elements.length>1000)throw Error();for(const e of o.elements){if(!names[e.type]||typeof e.text!=='string'||typeof e.href!=='string'||typeof e.bold!=='boolean'||!['left','center','right'].includes(e.align)||!color(e.color)||!(e.background==='transparent'||color(e.background)))throw Error();for(const k of ['x','y','w','h','fontSize','radius'])if(!Number.isFinite(e[k])||e[k]<0||e[k]>5000)throw Error();if(e.type==='image'&&(typeof e.src!=='string'||!/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(e.src)))throw Error();}return{name:o.name,width:o.width,height:o.height,background:o.background,elements:o.elements.map(e=>({...e,id:nextId++}))}}
$('loadInput').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>30*1024*1024)throw Error();const incoming=validate(JSON.parse(await file.text()));checkpoint();state=incoming;select(null);toast('プロジェクトを開きました')}catch{toast('有効なHTML Studioの保存ファイルを選んでください')}ev.target.value=''};
render();inspect();


