const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o));
const names={heading:'見出し',text:'テキスト',button:'ボタン',rectangle:'四角形',circle:'円',image:'画像',game:'ゲーム',code:'コードゲーム'};
let nextId=1,selected=null,scale=1,history=[],future=[],drag=null;
let pendingPress=null,partClipboard=null,pasteCount=0,selectedIds=new Set();
function selectedElements(){return state.elements.filter(e=>selectedIds.has(e.id))}
function selectionBounds(items){return {left:Math.min(...items.map(e=>e.x)),top:Math.min(...items.map(e=>e.y)),right:Math.max(...items.map(e=>e.x+e.w)),bottom:Math.max(...items.map(e=>e.y+e.h))}}
function moveSelection(before,dx,dy){const b=selectionBounds(before);dx=Math.max(-b.left,Math.min(state.width-b.right,Math.round(dx)));dy=Math.max(-b.top,Math.min(state.height-b.bottom,Math.round(dy)));for(const old of before){const e=state.elements.find(e=>e.id===old.id);if(e){e.x=old.x+dx;e.y=old.y+dy}}}
function copyParts(){partClipboard=clone(selectedElements());pasteCount=0;toast(partClipboard.length+'個のパーツをコピーしました')}
function duplicateParts(items,offset=20){if(!items.length)return;checkpoint();const b=selectionBounds(items),dx=Math.max(-b.left,Math.min(offset,state.width-b.right)),dy=Math.max(-b.top,Math.min(offset,state.height-b.bottom)),programIds=new Set(state.elements.filter(e=>e.type==='code').map(e=>e.programId));const copies=items.map(old=>{const e={...clone(old),id:nextId++,x:old.x+dx,y:old.y+dy};if(e.type==='code'){e.programId='game'+e.id;while(programIds.has(e.programId))e.programId+='_copy';programIds.add(e.programId)}return e});state.elements.push(...copies);selectMany(copies.map(e=>e.id))}
function partShortcutAllowed(target){return !target.closest('input,textarea,select,[contenteditable="true"]')&&!$('previewDialog').open&&!$('codeDialog').open}
function pastePart(){cancelPress();pasteCount++;duplicateParts(partClipboard,20*pasteCount);focusCanvas();toast(partClipboard.length+'個のパーツを貼り付けました')}
function cancelPress(){if(pendingPress)clearTimeout(pendingPress.timer);pendingPress=null;drag=null;$('selectionMarquee')?.remove()}
function focusCanvas(){$('canvas').focus({preventScroll:true})}
function canvasPoint(x,y){const r=$('canvas').getBoundingClientRect();return{x:Math.max(0,Math.min(state.width,(x-r.left)/scale)),y:Math.max(0,Math.min(state.height,(y-r.top)/scale))}}
function beginPress(p){if(p.id===null){select(null);drag={marquee:true,pointerId:p.pointerId,start:canvasPoint(p.x,p.y)};drawMarquee(drag.start);return}if(!state.elements.some(e=>e.id===p.id))return;if(!selectedIds.has(p.id))select(p.id);focusCanvas();drag={id:p.id,pointerId:p.pointerId,resize:p.resize&&selectedIds.size===1,startX:p.x,startY:p.y,before:clone(selectedElements()),saved:false};}
function drawMarquee(end){const a=drag.start,left=Math.min(a.x,end.x),top=Math.min(a.y,end.y),right=Math.max(a.x,end.x),bottom=Math.max(a.y,end.y);selectMany(state.elements.filter(e=>e.x<right&&e.x+e.w>left&&e.y<bottom&&e.y+e.h>top).map(e=>e.id));const box=document.createElement('div');box.id='selectionMarquee';box.setAttribute('aria-hidden','true');Object.assign(box.style,{left:left+'px',top:top+'px',width:right-left+'px',height:bottom-top+'px'});$('canvas').append(box)}
const make=(type,extra={})=>({id:nextId++,type,x:70,y:70,w:260,h:70,text:type==='heading'?'新しい見出し':type==='text'?'ここにテキストを入力してください。':type==='button'?'詳しく見る':'',fontSize:type==='heading'?36:16,color:'#272a40',background:['rectangle','circle','button'].includes(type)?'#7256e8':'transparent',radius:type==='circle'?500:type==='button'?10:0,bold:type==='heading',align:type==='button'?'center':'left',href:'',...extra});
let state={name:'はじめてのWebページ',width:1000,height:760,background:'#ffffff',elements:[make('text',{x:72,y:62,w:330,h:30,text:'YOUR NEXT CHAPTER',fontSize:14,bold:true,color:'#7456db'}),make('heading',{x:72,y:136,w:840,h:155,text:'ひらめきを、\nあなたのWebサイトに。',fontSize:57}),make('text',{x:76,y:330,w:680,h:80,text:'伝えたいことを、自由に並べよう。\n文字も、色も、レイアウトも。ここからは、あなた次第。',fontSize:20,color:'#7b7e90'}),make('button',{x:76,y:459,w:210,h:58,text:'ここからはじめる',color:'#ffffff',bold:true}),make('rectangle',{x:76,y:609,w:848,h:2,background:'#ecebf3'}),make('text',{x:76,y:643,w:650,h:32,text:'MADE WITH IMAGINATION  /  HTML STUDIO',fontSize:13,color:'#9798a7'})]};
function checkpoint(){history.push(clone(state));if(history.length>80)history.shift();future=[];updateHistory()}
function updateHistory(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function current(){return selectedIds.size===1?state.elements.find(e=>e.id===selected):undefined}
function elementStyle(e){return{left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px',fontSize:e.fontSize+'px',color:e.color,background:e.background,borderRadius:e.radius+'px',fontWeight:e.bold?'700':'400',textAlign:e.align}}
function render(){state.elements.forEach(e=>constrain(e));document.querySelectorAll('[data-width]').forEach(b=>b.classList.toggle('active',Number(b.dataset.width)===state.width));const c=$('canvas');c.replaceChildren();Object.assign(c.style,{width:state.width+'px',height:state.height+'px',background:state.background});for(const e of state.elements){const el=document.createElement('div');el.className='element'+(selectedIds.has(e.id)?' selected':'');el.dataset.id=e.id;el.tabIndex=0;el.setAttribute('aria-label',names[e.type]+': '+(e.text||''));Object.assign(el.style,elementStyle(e));const inner=document.createElement('div');inner.className='inner';if(e.type==='code'){inner.classList.add('game-placeholder');inner.textContent='</> '+e.text+'\n'+(e.language==='python'?'Python':'JavaScript')+' · '+e.programId+'\nコードを編集してゲームを作る'}else if(e.type==='game'){inner.classList.add('game-placeholder');inner.textContent='▶ '+e.text+'\n'+(e.gameMode==='dodge'?'矢印キー・タッチでよけよう':'動くターゲットをクリック')+'\n制限時間 '+e.duration+'秒 · プレビューでプレイ'}else if(e.type==='image'){const img=document.createElement('img');img.src=e.src;img.alt=e.text||'画像';inner.append(img)}else{inner.innerHTML=formattedText(e.text);if(e.type==='button'){inner.style.display='flex';inner.style.alignItems='center';inner.style.justifyContent=e.align==='left'?'flex-start':e.align==='right'?'flex-end':'center';inner.style.padding='8px'}}el.append(inner);if(e.id===selected){const tag=document.createElement('span');tag.className='element-tag';tag.textContent=names[e.type];const handle=document.createElement('span');handle.className='resize';el.append(tag,handle)}c.append(el)}fit();layers();updateHistory();$('projectName').value=state.name}
function fit(){const stage=$('stage'),z=$('zoom').value;scale=z==='fit'?Math.min(1,Math.max(.1,(stage.clientWidth-(innerWidth<760?24:64))/state.width)):Number(z);$('canvas').style.transform=`scale(${scale})`;$('canvasWrap').style.width=state.width*scale+'px';$('canvasWrap').style.height=state.height*scale+'px'}
function inspect(){const multi=selectedIds.size>1;$('multiFields').hidden=!multi;if(multi){$('elementFields').hidden=true;$('pageFields').hidden=true;$('inspectorTitle').textContent=selectedIds.size+'個を選択';$('kindBadge').textContent='MULTI';$('selectionStatus').textContent=selectedIds.size+'個のパーツを選択中';return}const e=current();$('codeFields').hidden=e?.type!=='code';$('buttonFields').hidden=e?.type!=='button';if(e?.type==='code')$('programId').value=e.programId;if(e?.type==='button'){$('buttonAction').value=e.buttonAction||'link';$('buttonEvent').value=e.buttonEvent||''}$('gameFields').hidden=e?.type!=='game';if(e?.type==='game'){for(const k of ['gameMode','duration','difficulty'])$(k).value=e[k]} $('elementFields').hidden=!e;$('pageFields').hidden=!!e;$('inspectorTitle').textContent=e?names[e.type]:'ページ設定';$('kindBadge').textContent=e?e.type.toUpperCase():'PAGE';$('selectionStatus').textContent=e?`${names[e.type]} · ${Math.round(e.w)} × ${Math.round(e.h)}`:'パーツを選んで編集';if(e){for(const key of ['x','y','w','h','fontSize','radius','color','align','href'])$(key).value=e[key];$('content').value=e.text;$('background').value=e.background==='transparent'?'#ffffff':e.background;$('transparent').checked=e.background==='transparent';$('bold').checked=e.bold;$('linkField').hidden=e.type!=='button';$('content').parentElement.hidden=['rectangle','circle'].includes(e.type)}else{$('pageColor').value=state.background;$('pageHeight').value=state.height;$('pageScroll').checked=state.scroll!==false}}
function selectMany(ids){selectedIds=new Set(ids);selected=ids.length===1?ids[0]:null;render();inspect()}
function select(id){selectMany(id===null?[]:[id])}
function layers(){$('layerList').replaceChildren();for(const e of [...state.elements].reverse()){const b=document.createElement('button');b.textContent=(e.text||names[e.type]).replaceAll('\n',' ');b.className=selectedIds.has(e.id)?'active':'';b.onclick=()=>select(e.id);$('layerList').append(b)}}
function add(type,extra={}){checkpoint();const e=make(type,{...(type==='code'?{w:640,h:480,text:'コードゲーム',background:'#151b32',color:'#ffffff',language:'javascript',code:codeSamples.javascript,programId:'game'+nextId}:{}),...(type==='game'?{w:600,h:440,text:'マイゲーム',background:'#171b35',color:'#ffffff',radius:16,gameMode:'click',duration:30,difficulty:2}:{}),x:Math.min(70,state.width-280),y:Math.round($('stage').scrollTop/scale+90),...extra});e.x=Math.max(0,e.x);if(type==='code'&&state.elements.some(p=>p.programId===e.programId))e.programId='game'+e.id;state.elements.push(e);select(e.id)}
document.querySelectorAll('[data-add]').forEach(b=>{b.onclick=()=>add(b.dataset.add);b.ondragstart=ev=>ev.dataTransfer.setData('text/plain',b.dataset.add)});
$('canvas').ondragover=ev=>ev.preventDefault();$('canvas').ondrop=ev=>{ev.preventDefault();const t=ev.dataTransfer.getData('text/plain');if(!['heading','text','button','rectangle','circle','game','code'].includes(t))return;const r=$('canvas').getBoundingClientRect();add(t,{x:Math.max(0,Math.round((ev.clientX-r.left)/scale)),y:Math.max(0,Math.round((ev.clientY-r.top)/scale))})};
$('canvas').tabIndex=0;
$('canvas').onpointerdown=ev=>{
 if(ev.button!==0||!ev.isPrimary)return;
 cancelPress();const el=ev.target.closest('.element');
 focusCanvas();
 ev.preventDefault();$('canvas').setPointerCapture(ev.pointerId);
 const p={id:el?Number(el.dataset.id):null,pointerId:ev.pointerId,resize:ev.target.classList.contains('resize'),x:ev.clientX,y:ev.clientY};
 pendingPress=p;p.timer=setTimeout(()=>{if(pendingPress===p){pendingPress=null;beginPress(p)}},350);
 if(p.resize){clearTimeout(p.timer);pendingPress=null;beginPress(p)}
};
window.addEventListener('pointermove',ev=>{
 if(pendingPress&&ev.pointerId===pendingPress.pointerId&&Math.hypot(ev.clientX-pendingPress.x,ev.clientY-pendingPress.y)>4){const p=pendingPress;clearTimeout(p.timer);pendingPress=null;beginPress(p)}
 if(!drag||ev.pointerId!==drag.pointerId)return;if(drag.marquee){drawMarquee(canvasPoint(ev.clientX,ev.clientY));return}const dx=(ev.clientX-drag.startX)/scale,dy=(ev.clientY-drag.startY)/scale;if(!drag.saved&&Math.abs(dx)+Math.abs(dy)<2)return;if(!drag.saved){checkpoint();drag.saved=true}if(drag.resize){const e=current();if(!e)return;e.w=Math.min(state.width-e.x,Math.max(20,Math.round(drag.before[0].w+dx)));e.h=Math.min(state.height-e.y,Math.max(20,Math.round(drag.before[0].h+dy)))}else{moveSelection(drag.before,dx,dy)}render();inspect()
});
window.addEventListener('pointerup',ev=>{if(pendingPress&&ev.pointerId===pendingPress.pointerId){if(pendingPress.id===null||!selectedIds.has(pendingPress.id))select(pendingPress.id);focusCanvas()}cancelPress()});
window.addEventListener('pointercancel',cancelPress);window.addEventListener('blur',cancelPress);
$('canvas').addEventListener('contextmenu',ev=>{ev.preventDefault();cancelPress();const el=ev.target.closest('.element');if(!el)return;if(!selectedIds.has(Number(el.dataset.id)))select(Number(el.dataset.id));remove();focusCanvas();toast('削除しました · Ctrl+Zで元に戻せます')});
for(const key of ['content','x','y','w','h','fontSize','radius','color','background','align','href','bold','transparent']){$(key).addEventListener(['content','href'].includes(key)?'input':'change',()=>{const e=current();if(!e)return;checkpoint();if(key==='content')e.text=$(key).value;else if(key==='bold')e.bold=$(key).checked;else if(key==='transparent')e.background=$(key).checked?'transparent':$('background').value;else if(['x','y','w','h','fontSize','radius'].includes(key)){const value=Number($(key).value);e[key]=Math.max(['w','h'].includes(key)?20:key==='fontSize'?8:0,Math.min(key==='fontSize'?200:5000,Number.isFinite(value)?value:0))}else e[key]=$(key).value;render();if(!['content','href'].includes(key))inspect()})}
$('pageColor').onchange=()=>{checkpoint();state.background=$('pageColor').value;render()};$('pageHeight').onchange=()=>{checkpoint();state.height=Math.min(5000,Math.max(300,Number($('pageHeight').value)||760));render();inspect()};$('projectName').onchange=()=>{checkpoint();state.name=$('projectName').value.trim()||'無題のページ';render()};
function remove(){if(!selectedIds.size)return;checkpoint();state.elements=state.elements.filter(e=>!selectedIds.has(e.id));select(null)}
$('delete').onclick=remove;$('duplicate').onclick=()=>duplicateParts(selectedElements());$('multiDelete').onclick=remove;$('multiDuplicate').onclick=()=>duplicateParts(selectedElements());
function reorder(delta){const i=state.elements.findIndex(e=>e.id===selected),j=i+delta;if(i<0||j<0||j>=state.elements.length)return;checkpoint();[state.elements[i],state.elements[j]]=[state.elements[j],state.elements[i]];render()}
$('forward').onclick=()=>reorder(1);$('backward').onclick=()=>reorder(-1);
function undo(){cancelPress();if(!history.length)return;future.push(clone(state));state=history.pop();select(null)}function redo(){cancelPress();if(!future.length)return;history.push(clone(state));state=future.pop();select(null)}$('undo').onclick=undo;$('redo').onclick=redo;
// Parts use an editor-local clipboard. Text fields retain native text shortcuts.
document.addEventListener('copy',ev=>{if(!partShortcutAllowed(ev.target)||!selectedIds.size)return;ev.preventDefault();copyParts();ev.clipboardData?.setData('text/plain','HTML Studio: '+selectedIds.size+' parts')});
document.addEventListener('paste',ev=>{if(!partShortcutAllowed(ev.target)||!partClipboard)return;ev.preventDefault();pastePart()});
document.addEventListener('keydown',ev=>{
 if(ev.isComposing||ev.target.closest('input,textarea,select,[contenteditable="true"]')||$('previewDialog').open||$('codeDialog').open)return;
 if(!(ev.ctrlKey||ev.metaKey)||ev.altKey)return;const key=ev.key.toLowerCase();
 if(key==='c'&&selectedIds.size){ev.preventDefault();copyParts()}
 if(key==='v'&&partClipboard){ev.preventDefault();pastePart()}
});
document.addEventListener('keydown',ev=>{if(!partShortcutAllowed(ev.target))return;const modifier=ev.ctrlKey||ev.metaKey;if(modifier&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo();return}if(modifier&&ev.key.toLowerCase()==='y'){ev.preventDefault();redo();return}if(ev.key==='Escape'){cancelPress();select(null);return}if(!selectedIds.size)return;if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();remove()}if(ev.key.startsWith('Arrow')){ev.preventDefault();checkpoint();const n=ev.shiftKey?10:1;moveSelection(clone(selectedElements()),ev.key==='ArrowRight'?n:ev.key==='ArrowLeft'?-n:0,ev.key==='ArrowDown'?n:ev.key==='ArrowUp'?-n:0);render();inspect()}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));$('parts').hidden=b.dataset.tab!=='parts';$('layers').hidden=b.dataset.tab!=='layers'});
document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>{checkpoint();state.width=Number(b.dataset.width);document.querySelectorAll('[data-width]').forEach(t=>t.classList.toggle('active',t===b));render();inspect();toast('キャンバス幅を変更し、すべてのパーツを枠内に収めました。')});$('zoom').onchange=fit;new ResizeObserver(fit).observe($('stage'));
$('imageAdd').onclick=()=>$('imageInput').click();$('imageInput').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;if(file.size>8*1024*1024){toast('画像は8MB以下で選んでください');return}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){toast('PNG・JPEG・WebP・GIFを選んでください');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const w=Math.min(400,state.width-40);add('image',{src:reader.result,w,h:Math.round(w*img.height/img.width),text:file.name});toast('画像を追加しました')};img.onerror=()=>toast('この画像を読み込めませんでした');img.src=reader.result};reader.readAsDataURL(file);ev.target.value=''};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeLink(s){try{const u=new URL(s);return ['https:','http:','mailto:','tel:'].includes(u.protocol)?s:''}catch{return s.startsWith('#')?s:''}}
function html(){
 state.elements.forEach(e=>constrain(e));
 const items=state.elements.map(e=>{
  const style=Object.entries(elementStyle(e)).map(([k,v])=>k.replace(/[A-Z]/g,l=>'-'+l.toLowerCase())+':'+v).join(';');
  const tag=e.type==='heading'?'h2':e.type==='button'?(e.buttonAction&&e.buttonAction!=='link'?'button':'a'):'div';
  const body=e.type==='code'?'<iframe class="code-game-frame" title="'+esc(e.text)+'" sandbox="allow-scripts" style="border:0;width:100%;height:100%" srcdoc="'+esc(codeDocument(e))+'"></iframe>':e.type==='game'?gameMarkup(e):e.type==='image'?'<img src="'+esc(e.src)+'" alt="'+esc(e.text)+'">':formattedText(e.text);
  return '<'+tag+' class="item" style="margin:0;'+esc(style)+(e.type==='button'?';display:flex;align-items:center;justify-content:'+(e.align==='left'?'flex-start':e.align==='right'?'flex-end':'center')+';padding:8px':'')+'"'+(e.type==='button'?(tag==='a'?' href="'+esc(safeLink(e.href)||'#')+'"':' type="button" data-studio-action="'+esc(e.buttonAction)+'" data-studio-target="'+esc(e.buttonEvent||'')+'"'):'')+'>'+body+'</'+tag+'>';
 }).join('');
 return '<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(state.name)+'</title><style>*{box-sizing:border-box}body{margin:0;background:'+state.background+';font-family:system-ui,sans-serif;overflow-x:hidden;overflow-y:'+(state.scroll===false?'hidden':'auto')+'}.page-shell{position:relative;margin:0 auto}.page{position:absolute;left:0;top:0;width:'+state.width+'px;height:'+state.height+'px;overflow:hidden;transform-origin:top left}.item{position:absolute;white-space:pre-wrap;line-height:1.35;overflow:hidden;text-decoration:none}img{display:block;width:100%;height:100%;object-fit:cover}'+gameStyles+'</style></head><body><div class="page-shell"><main class="page">'+items+'</main></div><script>('+resizeExport.toString()+')('+state.width+','+state.height+','+(state.scroll!==false)+');('+bootGames.toString()+')();('+routePrograms.toString()+')();<\/script></body></html>';
}
function resizeExport(width,height,scroll){const page=document.querySelector('.page'),shell=document.querySelector('.page-shell');function fit(){const scale=Math.min(1,document.documentElement.clientWidth/width,scroll?Infinity:window.innerHeight/height);page.style.transform='scale('+scale+')';shell.style.width=width*scale+'px';shell.style.height=height*scale+'px'}fit();new ResizeObserver(fit).observe(document.documentElement);window.addEventListener('resize',fit)}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>{download('index.html',html(),'text/html;charset=utf-8');toast('HTMLを書き出しました')};$('preview').onclick=()=>{$('previewDialog').showModal();$('previewFrame').srcdoc=html()};$('closePreview').onclick=()=>{$('previewFrame').srcdoc='';$('previewDialog').close()};$('save').onclick=()=>{download('html-studio-project.json',JSON.stringify({version:1,...state},null,2),'application/json');toast('プロジェクトを保存しました')};$('load').onclick=()=>$('loadInput').click();
function validate(o){const color=v=>/^#[0-9a-f]{6}$/i.test(v);if(o.version!==1||typeof o.name!=='string'||!color(o.background)||![390,1000].includes(o.width)||!Number.isFinite(o.height)||o.height<300||o.height>5000||!Array.isArray(o.elements)||o.elements.length>1000)throw Error();for(const e of o.elements){if(!Object.hasOwn(names,e.type)||typeof e.text!=='string'||typeof e.href!=='string'||typeof e.bold!=='boolean'||!['left','center','right'].includes(e.align)||!color(e.color)||!(e.background==='transparent'||color(e.background)))throw Error();for(const k of ['x','y','w','h','fontSize','radius'])if(!Number.isFinite(e[k])||e[k]<0||e[k]>5000)throw Error();if(e.type==='image'&&(typeof e.src!=='string'||!/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(e.src)))throw Error();}return{name:o.name,scroll:o.scroll!==false,width:o.width,height:o.height,background:o.background,elements:o.elements.map(e=>({...e,id:nextId++}))}}
$('loadInput').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>30*1024*1024)throw Error();const incoming=validate(JSON.parse(await file.text()));checkpoint();state=incoming;select(null);toast('プロジェクトを開きました')}catch{toast('有効なHTML Studioの保存ファイルを選んでください')}ev.target.value=''};
function constrain(e){
 const number=(v,f)=>Number.isFinite(v)?v:f;
 e.w=Math.min(state.width,Math.max(['game','code'].includes(e.type)?240:1,number(e.w,100)));e.h=Math.min(state.height,Math.max(['game','code'].includes(e.type)?280:1,number(e.h,100)));
 e.x=Math.max(0,Math.min(state.width-e.w,number(e.x,0)));e.y=Math.max(0,Math.min(state.height-e.h,number(e.y,0)));
 if(e.type==='code'){e.programId=String(e.programId||'game'+e.id).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40)||'game'+e.id;e.language=e.language==='python'?'python':'javascript';e.code=typeof e.code==='string'?e.code:''}
 if(e.type==='game'){e.gameMode=e.gameMode==='dodge'?'dodge':'click';e.duration=Math.max(5,Math.min(300,number(Number(e.duration),30)));e.difficulty=Math.max(1,Math.min(5,number(Number(e.difficulty),2)))}
}
for(const key of ['gameMode','duration','difficulty'])$(key).onchange=()=>{const e=current();if(e?.type!=='game')return;checkpoint();e[key]=key==='gameMode'?$(key).value:Number($(key).value);render();inspect()};
$('pageScroll').onchange=()=>{checkpoint();state.scroll=$('pageScroll').checked;toast(state.scroll?'長いページは縦にスクロールできます':'画面内にページ全体を収めます')};
$('extendPage').onclick=()=>{checkpoint();state.height=Math.min(5000,state.height+760);state.scroll=true;select(null);toast('ページを下に延長しました')};
$('pageSettings').onclick=()=>select(null);
render();inspect();
