// Self-contained game widgets. These functions are embedded in exported HTML.
const gameStyles=`.game-widget{height:100%;display:flex;flex-direction:column;white-space:normal;padding:14px;gap:8px;font:14px system-ui;color:inherit}.game-widget h3{margin:0;font-size:20px}.game-hud{display:flex;gap:10px;justify-content:space-between;flex-wrap:wrap}.game-field{position:relative;flex:1;min-height:30px;overflow:hidden;background:#ffffff0d;border:1px solid #ffffff33;border-radius:8px;touch-action:none}.game-field:focus-visible{outline:3px solid #f9d96b;outline-offset:-3px}.game-widget button{font:inherit;cursor:pointer;border:0;border-radius:8px;padding:8px 14px;background:#fff;color:#27243f}.game-target{position:absolute;width:40px;height:40px;padding:0!important;border-radius:50%!important;background:#f6cf61!important;color:#332a13!important}.game-player,.game-obstacle{position:absolute;width:24px;height:24px;border-radius:5px;background:#80f0d0;pointer-events:none}.game-obstacle{background:#ff708b}.game-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.game-message{margin:0;min-height:20px}.game-help{font-size:12px;opacity:.85;margin:0}`;
function gameMarkup(e){return '<section class="game-widget" data-game="'+e.gameMode+'" data-duration="'+e.duration+'" data-difficulty="'+e.difficulty+'"><h3>'+esc(e.text)+'</h3><div class="game-hud"><span>スコア <b data-score>0</b></span><span>残り <b data-time>'+e.duration+'</b> 秒</span></div><div class="game-field" tabindex="0" role="group" aria-label="ゲームエリア"></div><p class="game-message" aria-live="polite">スタートを押してね</p><div class="game-controls"><button data-start>スタート</button>'+(e.gameMode==='dodge'?'<button data-dir="-1" aria-label="左に移動">◀</button><button data-dir="1" aria-label="右に移動">▶</button>':'')+'</div><p class="game-help">'+(e.gameMode==='dodge'?'左右キー・左右ボタン・タッチで移動。赤い落下物をよけよう。':'黄色い的をクリック・タップ。キーボードでは的にTabで移動してEnter。')+'</p></section>'}
function bootGames(){
 document.querySelectorAll('[data-game]').forEach(root=>{
  const field=root.querySelector('.game-field'),start=root.querySelector('[data-start]'),scoreLabel=root.querySelector('[data-score]'),timeLabel=root.querySelector('[data-time]'),message=root.querySelector('.game-message');
  const mode=root.dataset.game,duration=Number(root.dataset.duration),difficulty=Number(root.dataset.difficulty);
  let running=false,score=0,elapsed=0,last=0,frame=0,spawn=0,objects=[],direction=0,playerX=.5,player=null,target=null;
  const unit=24,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const size=()=>({w:field.clientWidth,h:field.clientHeight});
  function finish(text){running=false;direction=0;cancelAnimationFrame(frame);message.textContent=text+' · スコア '+score;start.textContent='もう一度';if(target)target.disabled=true}
  function positionTarget(){const {w,h}=size();const side=Math.max(10,Math.min(40,w,h));target.style.width=side+'px';target.style.height=side+'px';target.style.left=Math.random()*Math.max(0,w-side)+'px';target.style.top=Math.random()*Math.max(0,h-side)+'px'}
  function positionPlayer(){const {w,h}=size();player.style.width=Math.min(unit,w)+'px';player.style.height=Math.min(unit,h)+'px';player.style.left=clamp(playerX*w-unit/2,0,w-unit)+'px';player.style.top=Math.max(0,h-unit-4)+'px'}
  function tick(now){if(!running)return;const dt=Math.min((now-last)/1000,.06);last=now;elapsed+=dt;timeLabel.textContent=Math.max(0,Math.ceil(duration-elapsed));if(elapsed>=duration){finish('クリア！');return}spawn+=dt;
   if(mode==='click'){if(spawn>Math.max(.5,2.8-difficulty*.4)){positionTarget();spawn=0}}
   else{const {w,h}=size();playerX=clamp(playerX+direction*dt*.8,Math.min(.5,unit/2/w),Math.max(.5,1-unit/2/w));positionPlayer();if(spawn>1-difficulty*.12){spawn=0;const el=document.createElement('div');el.className='game-obstacle';el.style.width=Math.min(unit,w)+'px';el.style.height=Math.min(unit,h)+'px';const x=Math.random()*Math.max(0,w-unit);field.append(el);objects.push({el,x,y:0})}for(const o of objects){o.y+=dt*(65+difficulty*35);o.x=clamp(o.x,0,w-unit);o.el.style.left=o.x+'px';o.el.style.top=o.y+'px';const px=clamp(playerX*w-unit/2,0,w-unit),py=Math.max(0,h-unit-4);if(o.x<px+unit&&o.x+unit>px&&o.y<py+unit&&o.y+unit>py){finish('ゲームオーバー');return}if(o.y>h){o.el.remove();score++;scoreLabel.textContent=score}}objects=objects.filter(o=>o.y<=h)}
   frame=requestAnimationFrame(tick);
  }
  start.onclick=()=>{cancelAnimationFrame(frame);field.replaceChildren();objects=[];score=0;elapsed=0;spawn=0;direction=0;playerX=.5;scoreLabel.textContent='0';timeLabel.textContent=duration;message.textContent='プレイ中';start.textContent='リスタート';running=true;if(mode==='click'){target=document.createElement('button');target.className='game-target';target.textContent='★';target.setAttribute('aria-label','ターゲット');target.onclick=()=>{if(running){score++;scoreLabel.textContent=score;positionTarget();spawn=0}};field.append(target);positionTarget()}else{player=document.createElement('div');player.className='game-player';field.append(player);positionPlayer()}field.focus();last=performance.now();frame=requestAnimationFrame(tick)};
  field.addEventListener('keydown',ev=>{if(mode==='dodge'&&['ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();direction=ev.key==='ArrowLeft'?-1:1}});
  field.addEventListener('keyup',ev=>{if(['ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();direction=0}});field.addEventListener('blur',()=>direction=0);
  function touchMove(ev){if(!running||mode!=='dodge')return;const rect=field.getBoundingClientRect();playerX=clamp((ev.clientX-rect.left)/rect.width,0,1);positionPlayer()}
  field.addEventListener('pointerdown',ev=>{if(mode==='dodge'){field.setPointerCapture(ev.pointerId);touchMove(ev)}});field.addEventListener('pointermove',ev=>{if(ev.buttons)touchMove(ev)});
  root.querySelectorAll('[data-dir]').forEach(button=>{button.style.touchAction='none';button.onpointerdown=ev=>{button.setPointerCapture(ev.pointerId);direction=Number(button.dataset.dir)};button.onpointerup=button.onpointercancel=()=>direction=0;button.onclick=()=>{if(running){playerX=clamp(playerX+Number(button.dataset.dir)*.07,0,1);positionPlayer()}}});
  document.addEventListener('visibilitychange',()=>{last=performance.now();direction=0});
 });
}
