(()=>{
 const status=$('saveStatus');status.style.display='block';
 const dialog=document.createElement('dialog');dialog.id='savedProjects';dialog.setAttribute('aria-label','クラウド保存');
 dialog.innerHTML=`<div class="dialog-bar"><b>クラウドに保存した作品</b><button id="closeSaved">閉じる ×</button></div>
 <p>同じアカウントでログインすると、別の端末でも作品を開けます。保存した作品は本人だけが閲覧できます。</p>
 <form id="cloudLogin"><label>メールアドレス<input id="cloudEmail" type="email" autocomplete="email" required></label><label>パスワード<input id="cloudPassword" type="password" autocomplete="current-password" minlength="8" required></label><div class="storage-actions"><button type="submit" id="cloudSignIn">ログイン</button><button type="button" id="cloudSignUp">新規登録</button></div><p>新規登録は8文字以上のパスワードを設定し、届いた確認メールを開いてください。現在、新規登録の確認メールはサイト管理者のSupabase組織に登録済みのアドレスが対象です。</p></form>
 <div id="cloudAccount" hidden><span id="cloudUser"></span> <button id="cloudSignOut">ログアウト</button></div>
 <p id="cloudMessage" role="status"></p><div id="savedList"></div>
 <div class="storage-actions"><button id="saveCurrentCloud">この作品を保存</button><button id="saveCopy">別の作品として保存</button><button id="refreshCloud">一覧を更新</button><button id="backupProject">ファイルにバックアップ</button><button id="importProject">保存ファイルを読み込む</button></div>`;
 document.body.append(dialog);
 const style=document.createElement('style');style.textContent='#savedProjects{width:min(680px,90vw);height:auto;max-height:90vh;padding:20px}#savedProjects p{font-size:13px;color:#666}#cloudLogin{max-width:430px}#cloudLogin label{display:block;margin:12px 0}#cloudLogin input{display:block;width:100%;margin-top:5px;padding:10px;box-sizing:border-box}#savedList{max-height:40vh;overflow:auto}.saved-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid #ddd}.saved-row strong{overflow-wrap:anywhere}.saved-row small{display:block;color:#777}.storage-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}#cloudMessage{white-space:pre-wrap}';document.head.append(style);
 let client,store,user=null,active=null,revision=null,last='',timer,busy=false,conflict=false,authEpoch=0;
 const initial=JSON.stringify(state),message=text=>{$('cloudMessage').textContent=text};
 const pointerKey=uid=>'html-studio-cloud-active:'+uid;
 function remember(){try{if(user&&active)localStorage.setItem(pointerKey(user.id),active)}catch{}}
 function showAccount(){const logged=!!user;$('cloudLogin').hidden=logged;$('cloudAccount').hidden=!logged;$('cloudUser').textContent=user?.email||'';for(const id of ['saveCurrentCloud','saveCopy','refreshCloud'])$(id).disabled=!logged||busy}
 function failure(error){const text=error.code==='CONFLICT'?error.message:'クラウドに保存・接続できませんでした。通信とログイン状態を確認してください。'+(error.message?'\n'+error.message:'');message(text);status.textContent=error.code==='CONFLICT'?'更新が競合しています':'未保存 — 再試行してください';return false}
 function changed(){return JSON.stringify(state)!==last}
 function schedule(){clearTimeout(timer);if(!changed())return;if(!user){status.textContent='ログインするとクラウドに保存できます';return}if(!active){status.textContent='「クラウドに保存」で保存を開始';return}if(conflict)return;status.textContent='未保存の変更があります';timer=setTimeout(()=>save(false),1200)}
 const oldRender=render;render=function(){oldRender();schedule()};
 document.addEventListener('input',event=>{if(!dialog.contains(event.target))schedule()});document.addEventListener('change',event=>{if(!dialog.contains(event.target))schedule()});
 $('projectName').addEventListener('input',()=>{state.name=$('projectName').value.trim()||'無題のページ';schedule()});
 window.addEventListener('beforeunload',event=>{if(changed()&&JSON.stringify(state)!==initial){event.preventDefault();event.returnValue=''}});
 async function save(copy=false){
  clearTimeout(timer);if(!user){dialog.showModal();message('ログインしてから保存してください。');return false}if(busy)return false;if(conflict&&!copy)return failure({code:'CONFLICT',message:'別の端末で更新されています。変更を残すには「別の作品として保存」を選んでください。'});
  if(!copy&&active&&!changed())return true;
  busy=true;showAccount();const epoch=authEpoch,uid=user.id,snapshot=JSON.stringify(state),id=copy||!active?crypto.randomUUID():active,version=copy||!active?null:revision;
  status.textContent='クラウドへ保存中…';
  try{const saved=await store.save({id,owner:uid,revision:version,name:state.name.slice(0,200),project:{version:1,...JSON.parse(snapshot)},html:html()});if(epoch!==authEpoch)return false;active=id;revision=saved.revision;last=snapshot;conflict=false;remember();status.textContent='クラウド保存済み '+new Date(saved.updated_at).toLocaleTimeString();message('保存しました。別の端末からも開けます。');return true}catch(error){if(epoch===authEpoch){if(error.code==='CONFLICT')conflict=true;failure(error)}return false}finally{busy=false;showAccount();if(!conflict&&JSON.stringify(state)!==snapshot)schedule()}
 }
 async function list(){if(!user||!store)return;const epoch=authEpoch;try{const rows=await store.list();if(epoch!==authEpoch)return;$('savedList').replaceChildren();if(!rows.length)$('savedList').textContent='まだ保存した作品はありません。';for(const row of rows){const item=document.createElement('div');item.className='saved-row';const label=document.createElement('div'),title=document.createElement('strong'),date=document.createElement('small'),button=document.createElement('button');title.textContent=row.name+(row.id===active?'（編集中）':'');date.textContent=new Date(row.updated_at).toLocaleString();label.append(title,date);button.textContent='開く';button.onclick=()=>open(row.id);item.append(label,button);$('savedList').append(item)}}catch(error){failure(error)}}
 async function open(id,restoring=false){if(busy)return;clearTimeout(timer);if(!restoring&&changed()&&JSON.stringify(state)!==initial){if(!await save(conflict||!active))return}busy=true;showAccount();const epoch=authEpoch,before=JSON.stringify(state);try{const row=await store.load(id);if(epoch!==authEpoch)return;if(JSON.stringify(state)!==before){message('読み込み中に編集されました。もう一度「開く」を押してください。');return}const incoming=validate(row.project);active=row.id;revision=row.revision;state=incoming;last=JSON.stringify(state);conflict=false;history=[];future=[];select(null);$('projectName').value=state.name;updateHistory();remember();status.textContent='クラウドの作品を開きました';dialog.close();toast('クラウドから作品を開きました')}catch(error){failure(error)}finally{busy=false;showAccount()}}
 async function account(session){const next=session?.user||null;if(next?.id===user?.id)return;authEpoch++;clearTimeout(timer);user=next;active=null;revision=null;last=initial;conflict=false;showAccount();$('savedList').replaceChildren();status.textContent=user?'クラウドに接続しました':'ログインするとクラウドに保存できます';if(user){await list();let id;try{id=localStorage.getItem(pointerKey(user.id))}catch{}if(id&&JSON.stringify(state)===initial)await open(id,true)}}
 $('save').onclick=()=>save();$('load').onclick=()=>{dialog.showModal();list()};$('closeSaved').onclick=()=>dialog.close();
 $('saveCurrentCloud').onclick=async()=>{if(await save())await list()};$('saveCopy').onclick=async()=>{if(await save(true))await list()};$('refreshCloud').onclick=list;
 $('backupProject').onclick=()=>download('html-studio-project.json',JSON.stringify({version:1,...state},null,2),'application/json');
 $('importProject').onclick=()=>{dialog.close();$('loadInput').click()};const oldImport=$('loadInput').onchange;$('loadInput').onchange=async event=>{const old=state;await oldImport(event);if(state!==old){clearTimeout(timer);active=null;revision=null;last='';conflict=false;schedule()}};
 async function authenticate(signup){if(!client){message('ログイン機能を読み込めませんでした。ページを再読み込みしてください。');return}if(!$('cloudLogin').reportValidity())return;$('cloudSignIn').disabled=$('cloudSignUp').disabled=true;message('接続中…');try{const credentials={email:$('cloudEmail').value.trim(),password:$('cloudPassword').value};const result=signup?await client.auth.signUp({...credentials,options:{emailRedirectTo:'https://rippy0311-afk.github.io/html-studio/'}}):await client.auth.signInWithPassword(credentials);if(result.error)throw result.error;$('cloudPassword').value='';message(signup&&!result.data.session?'確認メールを開いてからログインしてください。':'ログインしました。「この作品を保存」でクラウド保存を開始できます。');await account(result.data.session)}catch(error){message('ログイン・登録できませんでした。\n'+error.message)}finally{$('cloudSignIn').disabled=$('cloudSignUp').disabled=false}}
 $('cloudLogin').onsubmit=event=>{event.preventDefault();authenticate(false)};$('cloudSignUp').onclick=()=>authenticate(true);
 $('cloudSignOut').onclick=async()=>{if(busy)return;if(changed()&&active&&!await save())return;const {error}=await client.auth.signOut();if(error)message(error.message);else{message('ログアウトしました。');await account(null)}};
 try{client=supabase.createClient(studioCloudConfig.url,studioCloudConfig.key);store=new StudioCloudStore(client);client.auth.onAuthStateChange((_event,session)=>setTimeout(()=>account(session),0));client.auth.getSession().then(({data,error})=>{if(error)failure(error);else account(data.session)}).catch(failure);showAccount();status.textContent='ログインするとクラウドに保存できます'}catch(error){failure(error)}
})();
