const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict'), path = require('node:path');
const context = vm.createContext({acorn:require('../vendor/acorn.js')});
for (const file of ['text-commands.js','text-mode.js','text-assist-core.js']) vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
const predict = (source,caret=source.length) => context.textPredictions(source,caret);
assert.equal(predict('<setV').choices[0].name,'setVar');
assert.equal(predict('"setV'),null);
assert.equal(predict('<// setV'),null);
assert.equal(predict('<print("setV'),null);
assert.equal(predict('<tru').choices[0].insert,'true');
assert.equal(predict('<setVar("time",0)>\n<getVar("ti').choices[0].insert,'time');
assert.equal(predict('<setVar("time",0)>\n<ti').choices.find(c=>c.name==='time').insert,'getVar("time")');
assert.equal(predict('{class{hello{<print("ok")>}}}\n<hel').choices[0].insert,'hello()');
assert.equal(predict('<setV("a",0)>',5).choices[0].insert,'setVar');
assert.equal(context.textDiagnostics('"hello"\n<print(>')[0].line,2);
assert.equal(context.textDiagnostics('<const a = ;>\n<print(1 + )>')[1].line,2);
assert.equal(context.textDiagnostics('<const a = ;>\n<setV').length,2);
assert.equal(context.textDiagnostics('<const a = 0>\n<const a = 1>')[0].line,2);
assert.equal(context.textDiagnostics('<setVar("time",0)>\n<every(1,()=>{\n print(getVar("time"));\n})>').length,0);
const {program,lineMap} = context.compileTextMode(context.parseTextMode('"x"\n{class{hello{\n<missing()>\n}}}\n[RUN<hello()>]'));
assert.equal(lineMap[program.split('\n').findIndex(s=>s==='missing()')+1],3);
console.log('PASS command/class/variable/boolean predictions, quoted/comment context, existing parentheses, multiline syntax errors and source line mapping');
const unloaded = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','text-assist-core.js'),'utf8'),unloaded);
const unavailable = unloaded.textDiagnostics('<setVar("time", 0)>')[0];
assert.equal(unavailable.system,true);
assert.equal(unavailable.line,null);
assert.doesNotMatch(unavailable.message,/not defined/);
console.log('PASS missing runtime is a system-loading issue, not a source-line error');
